services:
  script-service:
    build: .
    container_name: script-service
    networks:
      - aismix_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.script.rule=Host(`script.aismix.com`)"
      - "traefik.http.routers.script.entrypoints=websecure"
      - "traefik.http.routers.script.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.script.loadbalancer.server.port=8000"

networks:
  aismix_web:
    external: true
