http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    aismix-ratelimit:
      rateLimit:
        average: 100
        burst: 50
    aismix-secure-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
    aismix-auth:
      basicAuth:
        users:
          - "aismix:$apr1$zyR3mwyK$FwXEESa3U18.ct0eMkGup1"
